// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMyYv-UUM3gXyMnxxVVH331ILE8bphPY',
    appId: '1:763597806647:web:f341f6e99e742f5ce973b2',
    messagingSenderId: '763597806647',
    projectId: 'bisabasa',
    authDomain: 'bisabasa.firebaseapp.com',
    storageBucket: 'bisabasa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakZlgaKCRzFofroCNHT1CincEkxJR7tk',
    appId: '1:763597806647:android:0d3779280ab7523be973b2',
    messagingSenderId: '763597806647',
    projectId: 'bisabasa',
    storageBucket: 'bisabasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASiGNNei99BrYXR5jP9eWnhvT8OzPSzbk',
    appId: '1:763597806647:ios:799f7ced35d65b70e973b2',
    messagingSenderId: '763597806647',
    projectId: 'bisabasa',
    storageBucket: 'bisabasa.firebasestorage.app',
    iosBundleId: 'com.example.bisabasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASiGNNei99BrYXR5jP9eWnhvT8OzPSzbk',
    appId: '1:763597806647:ios:799f7ced35d65b70e973b2',
    messagingSenderId: '763597806647',
    projectId: 'bisabasa',
    storageBucket: 'bisabasa.firebasestorage.app',
    iosBundleId: 'com.example.bisabasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMyYv-UUM3gXyMnxxVVH331ILE8bphPY',
    appId: '1:763597806647:web:f197d6d176a4710de973b2',
    messagingSenderId: '763597806647',
    projectId: 'bisabasa',
    authDomain: 'bisabasa.firebaseapp.com',
    storageBucket: 'bisabasa.firebasestorage.app',
  );

}