// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMTIKj3ijNcExTPzWQAfB3XkExwB2jkM',
    appId: '1:776508961923:web:70f845ba8e4e9ac6d317b6',
    messagingSenderId: '776508961923',
    projectId: 'flutter-sign-in-d4106',
    authDomain: 'flutter-sign-in-d4106.firebaseapp.com',
    storageBucket: 'flutter-sign-in-d4106.firebasestorage.app',
    measurementId: 'G-0TH2KC787D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaMTIKj3ijNcExTPzWQAfB3XkExwB2jkM',
    appId: '1:776508961923:android:demo',
    messagingSenderId: '776508961923',
    projectId: 'flutter-sign-in-d4106',
    storageBucket: 'flutter-sign-in-d4106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMTIKj3ijNcExTPzWQAfB3XkExwB2jkM',
    appId: '1:776508961923:ios:demo',
    messagingSenderId: '776508961923',
    projectId: 'flutter-sign-in-d4106',
    storageBucket: 'flutter-sign-in-d4106.firebasestorage.app',
    iosBundleId: 'com.example.bisabasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaMTIKj3ijNcExTPzWQAfB3XkExwB2jkM',
    appId: '1:776508961923:ios:demo',
    messagingSenderId: '776508961923',
    projectId: 'flutter-sign-in-d4106',
    storageBucket: 'flutter-sign-in-d4106.firebasestorage.app',
    iosBundleId: 'com.example.bisabasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMTIKj3ijNcExTPzWQAfB3XkExwB2jkM',
    appId: '1:776508961923:web:70f845ba8e4e9ac6d317b6',
    messagingSenderId: '776508961923',
    projectId: 'flutter-sign-in-d4106',
    authDomain: 'flutter-sign-in-d4106.firebaseapp.com',
    storageBucket: 'flutter-sign-in-d4106.firebasestorage.app',
    measurementId: 'G-0TH2KC787D',
  );
}